/**
 * Foundational modern-country knowledge: parse aliases + canonical identity + centroid.
 * Not a historical gazetteer. No 2-letter ISO codes (they collide with US states).
 */

export type ModernCountry = {
  id: string
  name: string
  aliases: string[]
  latitude: number
  longitude: number
}

export const MODERN_COUNTRIES: ModernCountry[] = [
  {
    id: 'united-states',
    name: 'United States',
    aliases: ['usa', 'u.s.a.', 'u.s.', 'us', 'united states of america', 'america'],
    latitude: 39.8283,
    longitude: -98.5795,
  },
  {
    id: 'mexico',
    name: 'Mexico',
    aliases: ['mexique', 'méxico'],
    latitude: 23.6345,
    longitude: -102.5528,
  },
  {
    id: 'canada',
    name: 'Canada',
    aliases: ['canada'],
    latitude: 56.1304,
    longitude: -106.3468,
  },
  {
    id: 'england',
    name: 'England',
    aliases: ['uk', 'united kingdom', 'great britain', 'britain'],
    latitude: 52.3555,
    longitude: -1.1743,
  },
  {
    id: 'scotland',
    name: 'Scotland',
    aliases: ['scotland'],
    latitude: 56.4907,
    longitude: -4.2026,
  },
  {
    id: 'wales',
    name: 'Wales',
    aliases: ['wales'],
    latitude: 52.1307,
    longitude: -3.7837,
  },
  {
    id: 'ireland',
    name: 'Ireland',
    aliases: ['eire'],
    latitude: 53.4129,
    longitude: -8.2439,
  },
  {
    id: 'france',
    name: 'France',
    aliases: ['france'],
    latitude: 46.2276,
    longitude: 2.2137,
  },
  {
    id: 'spain',
    name: 'Spain',
    aliases: ['espana', 'españa', 'espagne'],
    latitude: 40.4637,
    longitude: -3.7492,
  },
  {
    id: 'portugal',
    name: 'Portugal',
    aliases: ['portugal'],
    latitude: 39.3999,
    longitude: -8.2245,
  },
  {
    id: 'germany',
    name: 'Germany',
    aliases: ['deutschland', 'allemagne'],
    latitude: 51.1657,
    longitude: 10.4515,
  },
  {
    id: 'italy',
    name: 'Italy',
    aliases: ['italia', 'italie'],
    latitude: 41.8719,
    longitude: 12.5674,
  },
  {
    id: 'netherlands',
    name: 'Netherlands',
    aliases: ['the netherlands', 'nederland'],
    latitude: 52.1326,
    longitude: 5.2913,
  },
  {
    id: 'belgium',
    name: 'Belgium',
    aliases: ['belgique', 'belgien'],
    latitude: 50.5039,
    longitude: 4.4699,
  },
  {
    id: 'luxembourg',
    name: 'Luxembourg',
    aliases: ['luxembourg'],
    latitude: 49.8153,
    longitude: 6.1296,
  },
  {
    id: 'switzerland',
    name: 'Switzerland',
    aliases: ['schweiz', 'suisse', 'svizzera'],
    latitude: 46.8182,
    longitude: 8.2275,
  },
  {
    id: 'austria',
    name: 'Austria',
    aliases: ['österreich', 'osterreich', 'oesterreich'],
    latitude: 47.5162,
    longitude: 14.5501,
  },
  {
    id: 'poland',
    name: 'Poland',
    aliases: ['polska', 'pologne'],
    latitude: 51.9194,
    longitude: 19.1451,
  },
  {
    id: 'hungary',
    name: 'Hungary',
    aliases: ['magyarorszag', 'hongrie'],
    latitude: 47.1625,
    longitude: 19.5033,
  },
  {
    id: 'romania',
    name: 'Romania',
    aliases: ['romania', 'roumanie'],
    latitude: 45.9432,
    longitude: 24.9668,
  },
  {
    id: 'greece',
    name: 'Greece',
    aliases: ['grèce', 'grecia', 'ellada'],
    latitude: 39.0742,
    longitude: 21.8243,
  },
  {
    id: 'denmark',
    name: 'Denmark',
    aliases: ['danmark', 'danemark'],
    latitude: 56.2639,
    longitude: 9.5018,
  },
  {
    id: 'norway',
    name: 'Norway',
    aliases: ['norge', 'norvege'],
    latitude: 60.472,
    longitude: 8.4689,
  },
  {
    id: 'sweden',
    name: 'Sweden',
    aliases: ['sverige', 'suede'],
    latitude: 60.1282,
    longitude: 18.6435,
  },
  {
    id: 'finland',
    name: 'Finland',
    aliases: ['suomi', 'finlande'],
    latitude: 61.9241,
    longitude: 25.7482,
  },
  {
    id: 'iceland',
    name: 'Iceland',
    aliases: ['islande'],
    latitude: 64.9631,
    longitude: -19.0208,
  },
  {
    id: 'russia',
    name: 'Russia',
    aliases: ['russian federation', 'russie'],
    latitude: 61.524,
    longitude: 105.3188,
  },
  {
    id: 'ukraine',
    name: 'Ukraine',
    aliases: ['ukraine'],
    latitude: 48.3794,
    longitude: 31.1656,
  },
  {
    id: 'turkey',
    name: 'Turkey',
    aliases: ['turkiye', 'turquie'],
    latitude: 38.9637,
    longitude: 35.2433,
  },
  {
    id: 'australia',
    name: 'Australia',
    aliases: ['australia'],
    latitude: -25.2744,
    longitude: 133.7751,
  },
  {
    id: 'new-zealand',
    name: 'New Zealand',
    aliases: ['new zealand', 'aotearoa'],
    latitude: -40.9006,
    longitude: 174.886,
  },
  {
    id: 'brazil',
    name: 'Brazil',
    aliases: ['brasil', 'bresil'],
    latitude: -14.235,
    longitude: -51.9253,
  },
  {
    id: 'argentina',
    name: 'Argentina',
    aliases: ['argentina'],
    latitude: -38.4161,
    longitude: -63.6167,
  },
  {
    id: 'chile',
    name: 'Chile',
    aliases: ['chile'],
    latitude: -35.6751,
    longitude: -71.543,
  },
  {
    id: 'peru',
    name: 'Peru',
    aliases: ['peru', 'pérou'],
    latitude: -9.19,
    longitude: -75.0152,
  },
  {
    id: 'colombia',
    name: 'Colombia',
    aliases: ['colombia'],
    latitude: 4.5709,
    longitude: -74.2973,
  },
  {
    id: 'cuba',
    name: 'Cuba',
    aliases: ['cuba'],
    latitude: 21.5218,
    longitude: -77.7812,
  },
  {
    id: 'philippines',
    name: 'Philippines',
    aliases: ['philippines'],
    latitude: 12.8797,
    longitude: 121.774,
  },
  {
    id: 'china',
    name: 'China',
    aliases: ['china', 'prc'],
    latitude: 35.8617,
    longitude: 104.1954,
  },
  {
    id: 'japan',
    name: 'Japan',
    aliases: ['japan', 'nippon'],
    latitude: 36.2048,
    longitude: 138.2529,
  },
  {
    id: 'india',
    name: 'India',
    aliases: ['india', 'bharat'],
    latitude: 20.5937,
    longitude: 78.9629,
  },
  {
    id: 'south-africa',
    name: 'South Africa',
    aliases: ['south africa'],
    latitude: -30.5595,
    longitude: 22.9375,
  },
  {
    id: 'egypt',
    name: 'Egypt',
    aliases: ['egypt', 'egypte'],
    latitude: 26.8206,
    longitude: 30.8025,
  },
  {
    id: 'israel',
    name: 'Israel',
    aliases: ['israel'],
    latitude: 31.0461,
    longitude: 34.8516,
  },
  {
    id: 'panama',
    name: 'Panama',
    aliases: ['panama'],
    latitude: 8.538,
    longitude: -80.7821,
  },
]
