import type { FamilyEvent } from '../types'
import { familyMarriages } from '../data/familyMarriages'
import type { EventSynthesisKind } from './types'

const SPECIAL_SERVICE_NAMES = new Set([
  'Victor Manuel Ruiz',
  'Edwin Aloysius Hendry',
  'Craig B Ruiz',
])

/** Best-effort raw place string attached to a family event. */
export function eventPlaceRaw(event: FamilyEvent): string | null {
  if (event.kind === 'birth') {
    return event.person.birthPlace?.trim() || null
  }
  if (event.kind === 'death') {
    return event.person.deathPlace?.trim() || null
  }
  if (event.kind === 'marriage') {
    const marriage = familyMarriages.find(
      (m) =>
        m.husbandId === event.person.id &&
        (!event.spouse || m.wifeId === event.spouse.id) &&
        m.year === event.year,
    )
    return marriage?.place?.trim() || null
  }
  if (event.kind === 'move' || event.kind === 'service') {
    return event.detail.trim() || null
  }
  return null
}

export function classifyEventSynthesis(event: FamilyEvent): {
  kind: EventSynthesisKind
  notes: string[]
} {
  if (event.kind === 'birth' || event.kind === 'death') {
    return {
      kind: 'gedcom-person-vital',
      notes: ['Synthesized from person birth/death fields in familyDatabase.'],
    }
  }
  if (event.kind === 'move') {
    return {
      kind: 'inferred-move',
      notes: [
        'Inferred when birth and death placeRegion() differ and lifespan > 10 years.',
        'Not a direct GEDCOM migration tag.',
      ],
    }
  }
  if (event.kind === 'service') {
    if (SPECIAL_SERVICE_NAMES.has(event.person.name)) {
      return {
        kind: 'curated-special-service',
        notes: ['From curated SPECIAL_EVENTS in buildFamilyEvents (not full OCCU import).'],
      }
    }
    return {
      kind: 'unknown',
      notes: ['Service event without recognized curated special-event name.'],
    }
  }
  if (event.kind === 'marriage') {
    return {
      kind: 'curated-marriage',
      notes: ['From familyMarriages.ts (curated; not regenerated by import-gedcom.py).'],
    }
  }
  return { kind: 'unknown', notes: ['Unrecognized synthesis path.'] }
}
