import type { AtlasThinking } from '../types'

/**
 * Placeholder Atlas Thinking observations — replace with a pattern engine or API.
 * Not generated by a live AI service.
 */
export const placeholderAtlasThinking: AtlasThinking[] = [
  {
    id: 'chihuahua-gap',
    observation:
      'The family disappears for nearly a century before reappearing in Chihuahua.',
    recordCount: 11,
    confidence: 'Medium',
    relatedPersonIds: ['I112732308500', 'I112699495697', 'I112732308681'],
    relatedEventIds: [],
    yearStart: 1620,
    yearEnd: 1920,
    evidenceSummary:
      'Documented facts: 11 records list Chihuahua municipalities including Santa Isabel and Rosales between 1741 and 1915, with sparse coverage in the intervening generations.',
  },
  {
    id: 'migration-corridor',
    observation:
      'Most migrations followed existing settlement corridors rather than isolated moves.',
    recordCount: 18,
    confidence: 'Medium',
    relatedPersonIds: ['I18123023584', 'I18123023593', 'I18123023748'],
    relatedEventIds: [],
    yearStart: 1630,
    yearEnd: 1960,
    evidenceSummary:
      'Documented facts: 18 people carry birth and death places spanning England, Pennsylvania, New Jersey, Texas, and Chihuahua along a recurring westward arc.',
  },
  {
    id: 'victor-europe',
    observation:
      "Victor Ruiz represents the family's first documented connection to Europe.",
    recordCount: 9,
    confidence: 'High',
    relatedPersonIds: ['I18123023748'],
    relatedEventIds: [],
    yearStart: 1935,
    yearEnd: 1950,
    evidenceSummary:
      'Documented facts: Victor Manuel Ruiz (b. 1915) is associated with wartime service connected to the European air war through family research on the 388th Bomb Group.',
  },
  {
    id: 'local-continuity',
    observation:
      'Three generations remained within twenty miles of one another.',
    recordCount: 14,
    confidence: 'Medium',
    relatedPersonIds: ['I18123023593'],
    relatedEventIds: [],
    yearStart: 1880,
    yearEnd: 1940,
    evidenceSummary:
      'Documented facts: 14 Hendry and allied records list Camden County and nearby New Jersey places between 1890 and 1935 without distant relocations.',
  },
  {
    id: 'westward-not-south',
    observation: 'The family repeatedly moved west, but rarely south.',
    recordCount: 16,
    confidence: 'Medium',
    relatedPersonIds: ['I18123023584', 'I18123023593', 'I112732308681'],
    relatedEventIds: [],
    yearStart: 1630,
    yearEnd: 1950,
    evidenceSummary:
      'Documented facts: 16 records trace birth and death places moving westward from England through Pennsylvania, Texas, and Chihuahua without southern relocations.',
  },
  {
    id: 'earliest-thread',
    observation:
      'The earliest name opens a trail five centuries long—yet the sixteenth century rests on very few records.',
    recordCount: 3,
    confidence: 'Low',
    relatedPersonIds: ['I18150788585'],
    relatedEventIds: [],
    yearStart: 1470,
    yearEnd: 1520,
    evidenceSummary:
      'Documented facts: William Lowndes (b. about 1473) is the earliest dated birth. Only three records appear before 1600.',
  },
  {
    id: 'living-edge',
    observation:
      'The living generation compresses recent memory into a narrow band at the timeline edge.',
    recordCount: 6,
    confidence: 'High',
    relatedPersonIds: ['I18123023582', 'I18128930147'],
    relatedEventIds: [],
    yearStart: 1970,
    yearEnd: 2026,
    evidenceSummary:
      'Documented facts: Craig B Ruiz (b. 1975) and Mateo Thomas Santa Ruiz (b. 2011) anchor the present end of the documented record.',
  },
]
